- src/parser.rs
- testdata/add_oneliner
I encountered a PR that caused #11, after some digging it turns out, oneliner files (at least those) have deviant right hand side header.
The PR adds a regression test and fixes the issue by adding another named capture that is evaluated as a fallback since it should happen rarely.
> oneliners have deviant headers when adding files

- src/main.rs
- src/prr.rs
Hi all :wave:
This PR adds a local config file for a project. So, into the directory you can create a file named `.prr.toml` with this syntax below
```
[local]
repository = "danobi/prr-test-repo"
```
so to call commands just by PR number.
Call `prr get 6` instead of `prr danobi/prr-test-repo/6`
Also, if you re-define the `[prr]` section, this will override the main config file. Eg:
```
[prr]
workdir = "/tmp"
token = "..."
[local]
repository = "danobi/prr-test-repo"
```
will use `/tmp` folder as "reviews folder" only for this repository.
> Add local config file

- Cargo.lock
- Cargo.toml
- src/prr.rs
Having a dot is supported in GitHub, while the `SHORT` regex is too restrictive and disallows this. Support is added for repositories that contain a period or full stop.
There is no definitive guide to allowed characters for GitHub repositories, but you can piece together the allowed characters via moby/moby#679 and desktop/desktop#3090.
Tests were also added that verified the allowed characters in the repository name.
Pull request note: I'm not a Rust developer by day, please don't hesitate to provide pointed feedback.
> Support dots in repo names

- src/parser.rs
- src/review.rs
- testdata/empty_file
This input
> diff --git a/libbpf-cargo/src/btf/btf.rs b/libbpf-cargo/src/btf/btf.rs
> index 0000000..fffb281 100644
> --- /dev/null
> +++ b/libbpf-cargo/src/btf/btf.rs
> diff --git a/libbpf-cargo/src/test.rs b/libbpf-cargo/src/test.rs
> index 5b08843..82a0586 100644
> --- a/libbpf-cargo/src/test.rs
> +++ b/libbpf-cargo/src/test.rs
the parser treats as the header for the first file.
Fix this by recognizing the second "diff --git" line.
Fixes #23
> Fix path parsing after empty added file

- src/parser.rs
I saw a crash:
thread 'main' panicked at src/parser.rs:182:21:
internal error: entered unreachable code: Unexpected non-zero left-hand-side of git diff header. Expected 0.
Turns out that given hunk header
@@ -1,2 +3 @@
commit 3e9c247 (oneliners have deviant headers when adding files
(#12), 2022-08-18) interprets 3 as the length of the post-image.
This is wrong; 3 is the line where the post-image starts.
The length is implied to be 1 if omitted.
Such one-line diffs can be created with
$ printf '0\n1\n' > 1
$ printf '0\n2\n2' > 2
$ git diff --no-index 1 2 -U0
diff --git a/1 b/2
index d00491f..0cfbf08 100644
--- a/1
+++ b/2
@@ -2 +2 @@
-1
+2
> Fix diff parsing for one-line pre or post-image

- src/prr.rs
If you request changes or comment, the GH API requires at least one comment. This is not true for approvals. So allow comment-less approvals.
This closes #27.
> Allow approving PRs with no comment

- README.md
- examples/file_comment.prr
- src/parser.rs
- src/prr.rs
- src/review.rs
- testdata/file_comment
This PR adds support for file-level comments by commenting below the `diff --git` line, see the documentation for more usage details.
Note: I haven't actually tested the GitHub API portion of this yet, in case it fails catastrophically I didn't want to test on anything too "real". So I'm going to try it on this PR and see what happens.
Fixes #32
> Add support for file-level comments

- README.md
- src/prr.rs
`local.workdir` overrides the global `workdir` config. This allows per-directory workdir configuration.
Note this PR also makes a backwards incompatible change to disallow relative paths in `*.workdir` configs.
> Add `local.workdir` config override

- Cargo.lock
- Cargo.toml
This is mostly to allow hassle-free installation on NixOS and such. Attentive reader might ask: why not rustls then? At the time of writing, octocrab and reqwest support rustls, but git2 does not. It might be a good idea to try to switch to gitoxide in lie of git2, but that's going to be a larger change!
> Allow statically linking openssl

- .github/workflows/rust.yml
Various small tweaks. See individual commits for more details.
> Add more CI coverage

- src/review.rs
We cannot check the status of a new review directly because this will depend on the metadata that doesn't exist yet.
To fix this we check whether a review has a file with metadata already. If it does not, we assume it's a new one.
> src/review: fix review status checking logic for "get"

- book/src/install_binary.md
It said mdBook instead of prr.
> Fix crate name in install_binary.md

- src/review.rs
This helps provide a better error message for the user. Cuz if user corrupts quoted text and snip resolution is attempted, they'll get a generic:
Failed to resolve snips. Did you corrupt quoted text?
But if they hadn't used any snips, then they'll hit the validate_review_file() error check which provides line numbers and other helpful details.
This closes #49.
> Skip snip resolution if snips not used

- book/src/examples/spanned_inline_comment.md
It turns out code suggestions are interpreted by GitHub without any
addition (+) or deletion (-) markers. You simply have to attach a code
suggestion to a span with the updated code, and GitHub will calculate
the diff and render it.
> Adjust documentation showcasing code suggestion

- Cargo.lock
- Cargo.toml
- build.rs
- src/cli.rs
- src/main.rs
This commit adds the ability to generate manpages and shell completions by enabling the "clap_mangen" and "clap_complete" features respectively. These are disabled for default since they are platform-specific.
> Add ability to generate manpages and shell completions

- src/prr.rs
get_pr() downloads the PR and then deletes it. First, this does not work if the user is offline. Second, it's wasteful - why download then delete?
So use get_review() instead so we actually fetch an existing review.
> Use get_review() over get_pr() when removing reviews

- Cargo.lock
- Cargo.toml
bump git2 to 0.19.0 to build with libgit2 1.8
> chore(deps): update git2 to 0.19.0

- .github/workflows/rust.yml
- Cargo.toml
- build.rs
👋 I believe it’s generally better to generate completions and the man page by default whenever building the binary, rather than gating them behind feature flags. This simplifies the workflow and ensures all necessary assets are always available. 
Let me know what you think, thanks!
> build: enable completion and manpage generation by default

- book/src/config.md
- book/src/tutorial.md
- src/parser.rs
> chore: fix typos

- vim/ftplugin/prr.vim
- vim/syntax/prr.vim
I was running into some highlighting issues as shown in this [demo](https://asciinema.org/a/M3LwMg8ExJYdBhUxVVTqUoxeb).
I was able to fix it by replacing `foldmethod=syntax` with `foldmethod=expr` which allowed me to remove the `syn region` definitions in the syntax file.
The fold function is adapted from [vim-diff-fold](https://github.com/sgeb/vim-diff-fold/blob/master/ftplugin/diff.vim)
I took the liberty to make some `syn match` a bit more restrictive and also changed the highlight groups for `prrAdded` and `prrRemoved` to the standard diff groups which feels more natural when going through diffs.
Happy to discuss any modifications or improvement.
And thanks for this cool tool :smiley:
> vim: fix highlighting

- vim/syntax/prr.vim
Sorry, some small oversight on my part in previous PR.
Without `contained` the keywords like `comment` and `approve` would get highlighted anywhere.
With `contained` they get highlighted only on a line with `@prr`, as it was the case previously.
Edit: 2nd commit, might as well improve `prrTag` matching a bit while at it.
> vim: improve keyword syntax matching

- src/prr.rs
Remove the regex URI hack in favor of URI-based parsing, to accomodate the more complete github URLs.
Avoids me stripping a bunch of components to make the prr format happy; should fix #51
> proper url parsing
